# Generated by Django 4.2.23 on 2025-08-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureHuntQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Answer'), ('photo', 'Photo Upload'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('option_a', models.CharField(blank=True, max_length=200)),
                ('option_b', models.CharField(blank=True, max_length=200)),
                ('option_c', models.CharField(blank=True, max_length=200)),
                ('option_d', models.CharField(blank=True, max_length=200)),
                ('correct_answer', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='has_completed_hunt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(choices=[('charan', 'Charan'), ('shilpa_sandeep', 'Shilpa Sandeep'), ('shelna', 'Shelna'), ('sreekutty', 'Sreekutty'), ('arun', 'Arun'), ('aswin', 'Aswin'), ('martin', 'Martin'), ('firoz', 'Firoz'), ('najashree', 'Najashree'), ('sabareesh', 'Sabareesh'), ('suvindas', 'Suvindas'), ('jinusha', 'Jinusha'), ('sandeep', 'Sandeep'), ('prasanna_vineeth_mom', 'Prasanna (Vineeth Mom)'), ('athira_martin', 'Athira Martin'), ('vineeth', 'Vineeth'), ('shyam', 'Shyam'), ('saleena', 'Saleena'), ('kanika', 'Kanika'), ('chaithanya', 'Chaithanya'), ('aparna_dad', 'Aparna Dad'), ('sharan', 'Sharan'), ('athira_aswin', 'Athira Aswin'), ('shanish', 'Shanish'), ('aparna', 'Aparna'), ('shilpa_sabareesh', 'Shilpa Sabareesh'), ('remya', 'Remya'), ('aparna_mom', 'Aparna Mom')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('photo_answer', models.ImageField(blank=True, upload_to='treasure_hunt_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.treasurehuntquestion')),
            ],
            options={
                'unique_together': {('player', 'question')},
            },
        ),
    ]
