# Generated by Django 4.2.23 on 2025-08-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_treasurehuntquestion_player_has_completed_hunt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('performance_type', models.CharField(choices=[('dance', 'Dance Performance'), ('song', 'Song Performance'), ('skit', 'Skit/Drama')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='YouTube or other video link')),
                ('photo', models.ImageField(blank=True, upload_to='team_performances/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teamperformance')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'unique_together': {('voter', 'performance')},
            },
        ),
    ]
