# Generated by Django 4.2.23 on 2025-08-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teamperformance_performancevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeranswer',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='PerformanceVote',
        ),
        migrations.DeleteModel(
            name='TeamPerformance',
        ),
    ]
