# Generated by Django 4.2.23 on 2025-08-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playeranswer_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeranswer',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='reviewed_by',
        ),
    ]
