# Generated by Django 4.2.23 on 2025-08-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_player_is_online_player_session_key_player_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehuntquestion',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Upload an image for image-based questions', null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='treasurehuntquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('photo', 'Photo Upload'), ('multiple_choice', 'Multiple Choice'), ('image_text', 'Image Question (Text Answer)')], max_length=20),
        ),
    ]
