# Generated by Django 4.2.23 on 2025-08-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_image_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('group_dance', 'Group Dance'), ('group_song', 'Group Song')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('voting_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_team', models.CharField(choices=[('team_1', 'Team 1'), ('team_2', 'Team 2'), ('team_3', 'Team 3'), ('team_4', 'Team 4'), ('unassigned', 'Unassigned')], max_length=20)),
                ('performing_team', models.CharField(choices=[('team_1', 'Team 1'), ('team_2', 'Team 2'), ('team_3', 'Team 3'), ('team_4', 'Team 4'), ('unassigned', 'Unassigned')], max_length=20)),
                ('coordination_score', models.PositiveIntegerField(help_text='Group Coordination (1-10)')),
                ('selection_score', models.PositiveIntegerField(help_text='Song/Dance Selection (1-10)')),
                ('overall_score', models.PositiveIntegerField(help_text='Overall Performance (1-10)')),
                ('enjoyment_score', models.PositiveIntegerField(help_text='Enjoying the Event (1-10)')),
                ('comments', models.TextField(blank=True, help_text='Optional feedback')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'unique_together': {('event', 'voting_team', 'performing_team')},
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('team_1', 'Team 1'), ('team_2', 'Team 2'), ('team_3', 'Team 3'), ('team_4', 'Team 4'), ('unassigned', 'Unassigned')], max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'unique_together': {('event', 'team')},
            },
        ),
    ]
