# Generated by Django 4.2.23 on 2025-08-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_eventvote_eventparticipation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('team_1', 'Team 1'), ('team_2', 'Team 2'), ('team_3', 'Team 3'), ('team_4', 'Team 4'), ('unassigned', 'Unassigned')], max_length=20)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the scoring')),
                ('awarded_by', models.CharField(help_text='Admin who awarded the points', max_length=100)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'ordering': ['-points', 'team'],
                'unique_together': {('event', 'team')},
            },
        ),
    ]
