# Generated by Django 4.2.23 on 2025-08-26 (Manual migration - Fix null values)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_individual_event_models'),
    ]

    operations = [
        # Allow null values for IndividualEventVote score fields to fix admin form issue
        migrations.AlterField(
            model_name='individualeventvote',
            name='skill_score',
            field=models.PositiveIntegerField(blank=True, help_text='Skill/Technique (1-10)', null=True),
        ),
        migrations.AlterField(
            model_name='individualeventvote',
            name='creativity_score',
            field=models.PositiveIntegerField(blank=True, help_text='Creativity/Originality (1-10)', null=True),
        ),
        migrations.AlterField(
            model_name='individualeventvote',
            name='presentation_score',
            field=models.PositiveIntegerField(blank=True, help_text='Presentation/Stage Presence (1-10)', null=True),
        ),
        migrations.AlterField(
            model_name='individualeventvote',
            name='overall_score',
            field=models.PositiveIntegerField(blank=True, help_text='Overall Performance (1-10)', null=True),
        ),
    ]
