# Generated by Django 4.2.23 on 2025-08-26 (Manual migration - Team Event Participation)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fix_individual_vote_null_fields'),
    ]

    operations = [
        # Add new fields to EventScore model for participation tracking
        migrations.AddField(
            model_name='eventscore',
            name='points_per_participant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Points awarded per participating player', max_digits=5),
        ),
        migrations.AddField(
            model_name='eventscore',
            name='auto_calculate_points',
            field=models.BooleanField(default=False, help_text='Automatically calculate total points based on participants'),
        ),
        
        # Create TeamEventParticipation model
        migrations.CreateModel(
            name='TeamEventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated', models.BooleanField(default=False, help_text='Did this player participate?')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about participation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.eventscore')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'ordering': ['player__name'],
                'unique_together': {('event_score', 'player')},
            },
        ),
    ]
