name: Keep App + DB Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Login and Ping Admin + DB
        run: |
          for i in {1..5}; do
            echo "Login attempt $i at $(date)"
            
            # Login to Django admin and save cookies
            curl -s -c cookies.txt -d "username=OnamAdmin&password=ThanthaVibe123&next=/custom-admin/" \
              -X POST https://onam-celebration.onrender.com/custom-admin/login/ > /dev/null

            # Use cookie to hit authenticated/admin endpoints
            curl -s -b cookies.txt https://onam-celebration.onrender.com/custom-admin/ > /dev/null

            # Hit other DB-backed endpoints
            curl -s -b cookies.txt https://onam-celebration.onrender.com/events/ > /dev/null
            curl -s -b cookies.txt https://onam-celebration.onrender.com/about/ > /dev/null
            curl -s -b cookies.txt https://onam-celebration.onrender.com/select-player/ > /dev/null

            echo "Ping cycle $i done."
            sleep 10
          done
          echo "All 5 login + ping cycles completed."
