name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:         # lets you run it manually from the Actions tab

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        env:
          URL: https://onam-celebration.onrender.com/
        run: |
          echo "Pinging $URL"
          # try twice in case the first request wakes a sleeping instance
          for i in 1 2; do
            curl -fsS "$URL" > /dev/null && echo "OK" && exit 0
            sleep 15
          done
          # don't fail the workflow if site is momentarily unreachable
          echo "Ping failed (will try again next run)"; exit 0
