name: Keep App + DB Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: self-hosted
    steps:
      - name: Ping app & DB-backed endpoints
        run: |
          while true; do
            echo "Logging in..."
            curl -s -c cookies.txt -d "username=OnamAdmin&password=ThanthaVibe123" \
              https://onam-celebration.onrender.com/custom-admin/login/ > /dev/null

            echo "Pinging DB-backed URLs..."
            curl -s -b cookies.txt https://onam-celebration.onrender.com/events/ > /dev/null
            curl -s -b cookies.txt https://onam-celebration.onrender.com/custom-admin/ > /dev/null
            curl -s -b cookies.txt https://onam-celebration.onrender.com/about/ > /dev/null
            curl -s -b cookies.txt https://onam-celebration.onrender.com/select-player/ > /dev/null

            echo "Ping done at $(date)"
            sleep 600   # wait 10 min
          done
